language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

before_script:
  - npm install -D
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer require "phpunit/phpunit=5.6.*"
    else
      composer require "phpunit/phpunit=7.*"
    fi
  - cat js/script.js|md5sum|cut -d ' ' -f 1 > _script_sum.before

script:
- npm run jsmin
- npm run test
- cat js/script.js|md5sum|cut -d ' ' -f 1 > _script_sum.after
- diff _script_sum.before _script_sum.after
- ./vendor/bin/phpunit
